"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Braces, Database, GitBranch, ShieldCheck, Smartphone, WalletCards, Webhook } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";

const nodes = [
  { id: "deel", eyebrow: "Source plane", title: "Deel API Sandbox", icon: Database, summary: "Versioned workforce data and signed lifecycle events.", endpoint: "GET /contracts • GET /payments • POST /webhooks/deel", security: "Server-side bearer token • HMAC-SHA256 webhook verification", latency: "Network-dependent • request provenance captured", detail: "Contracts, worker identity, payments and status changes are normalized into a vendor-neutral workforce event model. Payment access remains permission-dependent with a deterministic signed-event fallback for the public demonstration." },
  { id: "risk", eyebrow: "Intelligence plane", title: "PayGraph Risk Engine", icon: Braces, summary: "Point-in-time features, policy execution and explainable limits.", endpoint: "POST /v1/profiles • POST /v1/decisions • POST /v1/events", security: "Least-privilege service identity • encrypted feature snapshots", latency: "184ms illustrative decision • <200ms production objective", detail: "The engine combines deterministic policy rules with governed model outputs. Every result retains the input snapshot, policy and model versions, reason codes, timestamp and approval authority." },
  { id: "lender", eyebrow: "Execution plane", title: "Lender Routing Core", icon: WalletCards, summary: "Match eligible decisions to regulated capital and product policy.", endpoint: "POST /v1/routes • POST /v1/offers • GET /v1/partners", security: "Jurisdiction allow-lists • consent and purpose binding", latency: "Target <75ms routing decision", detail: "Routing evaluates geography, lender appetite, product constraints, price and available capital. The licensed lender remains responsible for capital, disclosures, servicing, reporting and regulatory obligations." },
  { id: "worker", eyebrow: "Experience plane", title: "Worker App UI", icon: Smartphone, summary: "Consent, offers, explanations and lifecycle servicing.", endpoint: "GET /v1/offers/{id} • GET /v1/decisions/{id}/reasons", security: "Tokenized identity • field minimization • consent receipts", latency: "Target <2s event-to-UI update", detail: "Workers see only eligible offers, plain-language explanations and current availability. Adverse outcomes surface consistent reason codes and jurisdiction-appropriate notices." },
] as const;

export default function ArchitecturePage() {
  const [selected, setSelected] = useState<(typeof nodes)[number] | null>(null);
  return <main className="architecture-page interactive-architecture">
    <header className="topbar"><Link href="/" className="brand"><span className="brand-mark"><GitBranch size={19}/></span><span>PayGraph <b>CreditOS</b></span></Link><nav><Link href="/"><ArrowLeft size={13}/> Product</Link><Link href="/demo">Demos</Link><Link href="/integrations/deel">Deel integration</Link></nav></header>
    <section className="architecture-hero"><p className="eyebrow"><GitBranch size={14}/> Interactive ecosystem architecture</p><h1>Follow a decision from workforce signal to regulated execution.</h1><p>Select any node to inspect its API contract, security boundary, latency objective and operating responsibility.</p></section>
    <section className="architecture-pipeline" aria-label="Deel ecosystem data flow">
      {nodes.map((node, index) => { const Icon = node.icon; return <div className="pipeline-segment" key={node.id}><button onClick={() => setSelected(node)}><span>{String(index + 1).padStart(2,"0")} • {node.eyebrow}</span><Icon/><h2>{node.title}</h2><p>{node.summary}</p><strong>Inspect node <ArrowRight/></strong></button>{index < nodes.length - 1 && <div className="pipeline-arrow"><ArrowRight/></div>}</div>; })}
    </section>
    <section className="architecture-assurance"><div><ShieldCheck/><span><b>Governed end to end</b><small>Source provenance, consent, versioned decisions and delegated authority</small></span></div><div><Webhook/><span><b>Event-driven controls</b><small>Idempotency, signed webhooks and exposure updates tied to operational events</small></span></div><div><Database/><span><b>Data minimization</b><small>Purpose-bound fields, retention controls and isolated lender routing</small></span></div></section>
    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent className="architecture-dialog">{selected && <><DialogHeader><span className="dialog-eyebrow">{selected.eyebrow}</span><DialogTitle>{selected.title}</DialogTitle><DialogDescription>{selected.detail}</DialogDescription></DialogHeader><div className="dialog-contract"><div><span>API surface</span><code>{selected.endpoint}</code></div><div><span>Security</span><code>{selected.security}</code></div><div><span>Performance</span><code>{selected.latency}</code></div></div><p className="dialog-boundary"><ShieldCheck/> Reference architecture and production objectives; the public prototype does not claim production scale or regulatory approval.</p></>}</DialogContent></Dialog>
  </main>;
}
